# Generated by Django 5.1 on 2024-11-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0035_alter_totaloperatingtime_equipment_name'),
        ('mro_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadinspection',
            name='equipment_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
    ]
