# Generated by Django 5.1 on 2024-11-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0040_alter_equipment_stop_status'),
        ('mro_services', '0002_alter_threadinspection_equipment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала TO/ремонта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания TO/ремонта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен')], default='IN_PROGRESS', verbose_name='Статус ремонта')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='equipment.equipment')),
            ],
        ),
    ]
