# Generated by Django 5.1 on 2024-11-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mro_services', '0003_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Ремонт', 'verbose_name_plural': 'Ремонты'},
        ),
        migrations.AlterModelOptions(
            name='threadinspection',
            options={'verbose_name': 'Дефектоскопия', 'verbose_name_plural': 'Дефектоскопия'},
        ),
    ]
