# Generated by Django 4.2 on 2023-06-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('SURF', 'Наземное'), ('BOTTOM', 'Забойное')], max_length=6),
        ),
    ]
