# Generated by Django 4.2 on 2023-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Свойства оборудования', 'verbose_name_plural': 'Свойства оборудования'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Производитель'),
        ),
    ]
