# Generated by Django 4.2 on 2023-06-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipmenttype_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='equipment_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='properties',
            field=models.ManyToManyField(to='equipment.property', verbose_name='Свойства'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('SURF', 'Наземное'), ('BOTTOM', 'Забойное')], max_length=6),
        ),
    ]
