# Generated by Django 4.2 on 2023-06-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipmenttype_equipment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='properties',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='properties',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.property', verbose_name='Свойства'),
            preserve_default=False,
        ),
    ]
