# Generated by Django 4.2 on 2023-06-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_equipmenttype_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='properties',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='is_hull',
            field=models.BooleanField(null=True, verbose_name='Корпусное'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='type',
            field=models.CharField(choices=[('SURF', 'Наземное'), ('BOTTOM', 'Забойное')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.vendor'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
