# Generated by Django 4.2 on 2023-06-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmenttype_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Замковая резьба')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=25, verbose_name='Заводской номер')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='threaded_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.threadconnection'),
        ),
    ]
