# Generated by Django 4.2 on 2023-06-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_threadconnection_equipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadconnection',
            options={'verbose_name': 'Замковая резьба', 'verbose_name_plural': 'Замковые резьбы'},
        ),
    ]
