# Generated by Django 4.2 on 2023-06-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_threadconnection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
