# Generated by Django 4.2 on 2023-06-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_equipmentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentcategory'),
        ),
    ]
