# Generated by Django 4.2 on 2023-09-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipmenttype_equipment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='threaded_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.threadconnection', verbose_name='Замковая резьба'),
        ),
    ]
