# Generated by Django 4.2 on 2023-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_operatingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingtime',
            name='circulation',
            field=models.IntegerField(verbose_name='Часы циркуляции за рейс'),
        ),
        migrations.AlterField(
            model_name='operatingtime',
            name='meters',
            field=models.IntegerField(verbose_name='Часы циркуляции за рейс'),
        ),
        migrations.AlterField(
            model_name='operatingtime',
            name='screw_up',
            field=models.SmallIntegerField(verbose_name='Свинчиваний'),
        ),
    ]
