# Generated by Django 4.2 on 2023-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_operatingtime_circulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingtime',
            name='meters',
            field=models.IntegerField(verbose_name='Пробурено метров за рейс'),
        ),
    ]
