# Generated by Django 4.2 on 2023-09-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_rename_equipment_operatingtime_equipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingtime',
            old_name='equipment_type',
            new_name='equipment',
        ),
    ]
