# Generated by Django 4.2 on 2023-09-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_rename_equipment_type_operatingtime_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatingTime',
        ),
    ]
