# Generated by Django 4.2 on 2023-09-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_delete_operatingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='type',
        ),
    ]
