# Generated by Django 4.2 on 2023-09-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_equipmenttype_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
