# Generated by Django 4.2 on 2023-09-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_delete_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='is_hull',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='threaded_connection',
        ),
    ]
