# Generated by Django 4.2 on 2023-09-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='equipment_category',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
    ]
