# Generated by Django 5.1 on 2024-08-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_remove_equipmenttype_equipment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=25, verbose_name='Заводской номер')),
                ('inventory_number', models.CharField(max_length=25, verbose_name='Инвентарный номер')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Тип оборудования')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.location', verbose_name='Местонахождение')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.vendor', verbose_name='Производитель')),
            ],
        ),
    ]
