# Generated by Django 5.1 on 2024-09-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Категория'),
        ),
    ]
