# Generated by Django 5.1 on 2024-10-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_equipmenttype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('equipment_type', 'serial_number')},
        ),
    ]
