# Generated by Django 5.1 on 2024-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='equipment_types', to='equipment.tags', verbose_name='Теги'),
        ),
    ]
