# Generated by Django 5.1 on 2024-10-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_tags_equipmenttype_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
