# Generated by Django 5.1 on 2024-11-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
