# Generated by Django 5.1 on 2024-11-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0030_alter_tag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.CreateModel(
            name='TotalOperatingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_circulation', models.IntegerField(verbose_name='Часы общее')),
                ('total_meters', models.IntegerField(verbose_name='Метры общее')),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Общие наработки',
                'verbose_name_plural': 'Общие наработки',
            },
        ),
        migrations.CreateModel(
            name='AssemblyRunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.IntegerField(verbose_name='Часы циркуляции за рейс')),
                ('meters', models.IntegerField(verbose_name='Пробурено метров за рейс')),
                ('operation_date', models.DateField(verbose_name='Дата окончания рейса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Опреатор')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.totaloperatingtime', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Наработка за рейс',
                'verbose_name_plural': 'Наработки за рейс',
            },
        ),
    ]
