# Generated by Django 5.1 on 2024-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_alter_equipment_equipment_type_totaloperatingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaloperatingtime',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
