# Generated by Django 5.1 on 2024-11-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_totaloperatingtime_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaloperatingtime',
            name='equipment_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
