# Generated by Django 5.1 on 2024-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_alter_totaloperatingtime_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyruntime',
            name='circulation',
            field=models.PositiveIntegerField(verbose_name='Часы циркуляции за рейс'),
        ),
        migrations.AlterField(
            model_name='assemblyruntime',
            name='meters',
            field=models.PositiveIntegerField(verbose_name='Пробурено метров за рейс'),
        ),
        migrations.AlterField(
            model_name='totaloperatingtime',
            name='total_circulation',
            field=models.PositiveIntegerField(default=0, verbose_name='Часы общее'),
        ),
        migrations.AlterField(
            model_name='totaloperatingtime',
            name='total_meters',
            field=models.PositiveIntegerField(default=0, verbose_name='Метры общее'),
        ),
    ]
