# Generated by Django 5.1 on 2024-11-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_alter_assemblyruntime_circulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaloperatingtime',
            name='equipment_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totaloperatingtime', to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
