# Generated by Django 5.1 on 2024-11-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0035_alter_totaloperatingtime_equipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.BooleanField(default=True, help_text='13216', verbose_name='Стоп-статус'),
        ),
    ]
