# Generated by Django 5.1 on 2024-11-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_equipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='status',
            new_name='stop_status',
        ),
    ]
