# Generated by Django 5.1 on 2024-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0039_alter_equipment_stop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='stop_status',
            field=models.CharField(choices=[('STOP', 'СТОП!'), ('NORMAL', 'НОРМА'), ('REPAIR', 'В ремонте')], default='NORMAL', verbose_name='Стоп-статус'),
        ),
    ]
