# Generated by Django 5.1 on 2024-11-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0040_alter_equipment_stop_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
